### PR TITLE
UPSTREAM: <carry>: Remove .dockerignore

### PR DESCRIPTION
**Pull request by alexander-demichev**
Currently, the vendor directory is ignored because `.dockerignore` only allows certain files. I removed the whole file to avoid this behavior in the future because we don't know how this file can change.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Can you add a PR description so that we can remember in the future why we are removing this vs just adding an extra line to it to include the vendor

**Comment by alexander-demichev** [comment]
@JoelSpeed done :)

**Pull request merged**
