### PR TITLE
UPSTREAM: <carry>: openshift: Drop ssh SSHPrivateKey

### PR DESCRIPTION
**Pull request by enxebre**
ssh keys are managed out of the box by mco in Openshift. Additionally as a machine API consumer you can inject your public ssh key via API. The private key is unused.

### CODE REVIEW

**Comment by ingvagabund** [comment]
```
$ grep -rn "sshPrivateKey"
Binary file bin/manager matches
cmd/clusterctl/examples/azure/out/machines.yaml:38:      sshPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdUJzUjNlZnlTbmtWOUh6ZFBzWE4rY3NTcjVLS0E5S0NMeGJBYmR4dWQyU0wzakphCmVTWWdPRlRoZTI5c2FiMy8wQnBtWDJJc2NFVjlNRS91RlV1dFZsVE1obUJCenFUajNQL2RYMHF2UEp0bUovZ0cKbDBrQzBwV1dWUlNDK3BmcU01L1VBckdTTVl5V1hUSndEVXo3MTFkWTNDRWlNZkgwaVNjbmc3MXhFbWd3bkxsZQp6bnU2TURIbEdaY2ZrengzYWp2Y1JMdmFwd3hGME0rU0JEd0F0Q3lFUWJtNjIxSXVEM2dSRVVHOGp6OEdiVWFECk80eElMWncxd3E1VjVzK2pnc09iRzRUQk9BUVVHRzFkRFZnY0VjcjVhME1kcG5PaHVxM1BOcy9aU05neVFyeUsKN0hSSisrL2ozdkcyWmkxRHUxaXRSQUs4SlZuQUczakhXZ0hhT3dJREFRQUJBb0lCQVFDdDlNWDVDd1NnNGJDaApCcXAyZWFpWjhndUI0ZENPdEFWV1FRVXB5VEtIbFhXalNhaTYrQTlScXNJelE2RUllUUtSdTZBbldEZnREWHV3CmZwWFRnV0lUUktUTUEzK3FwWnE0WXZyazQwaVkxNnk2NzF3cTdrM0FkSjlMWE1vMXhmMEJNbSs4NjlQYkJaKysKQjc1Z2t2RVRFL0ZlYmVCRm1QMFo2dWtuVFlUZGdnSGNHaDFHbU1zcDlHUFcrZkJ1TmVkNGxSSkdUcU5mVWJaeApEZDFvbkJqT3Z2eDF3NDk2UHdsYTlxRkwwRlBZMkg4YjdKM1NramZmTS91RmFWbVZGbTAvQ1pWdHMvWDUzR1ZIClBId2w3ZU5lOWNIQ2VYWFFNRzk3d05LSm9wL0MyRWo3NjY4NHJSVG1QVzUxV2FWTFA2SmQ4b3k3Um00WU52dTAKd0o5bk1PaUJBb0dCQU9nd2syYTQ2ZU16OHlMV2JEdE5McnRvdjZYSEYveTI1NjBBUHQreEMvOXdyMVo3QWJSQgpBMWJkb0ZyYzJ2bDh1UnpTVW93TTc4SFNQTk5Kamg5VVVjYWhFN3pvOTRaL0RiRkFRa04rSmh6K2hWeHY2amhrClR0VXhpUVBaSDBLVFppUEpta25CZlJnUUtoWmhiN0NiL2pyZ0IrNjEzdWFkd3pGcUtZL3lEaHBSQW9HQkFNcjgKTW02TVR4dXV4aUtLTjVQYlJMbytIemVFdzNZSUlmNVIrbEluMHFhdW1KbDFTeVVmR2ZWMjdvZm93ZGlNWEtOSwpjRHE0VjhvWnhmY1l0d3U3bmgyZGxCRi9EMUtUdG5HRGd1Q3FCb1JPT0RML3hBUmp2SVdUeG42UGp3d1B3Q2lkCnl0Qko5QnpiUGtBOXl1L3N5bU1zQnBuQkUxZDJOREwvMXVXZUtEekxBb0dBZnhZdlo5Y29kV3AyMXdla0grVkUKQWVING0rVllWTU5NRlY0QUMvSGREa2lBUUFaOXpVcVVhRlJRTTh1VXMxKzM5bldNSnduaHBTWE1reDA4aEJ0agoweU5SS1dJZU1XaVRkd1FrQU1zb1UxQmdjRkwxVVQ1ZUE4VGtLTTRMbFNZV2p0b0c3LzNPMlgvbmVXNkZjcFkvClZieFB1ekdpdW5sNVlDK3FaaFpuNzdFQ2dZRUF5WlVEa0gyTzRuTURHYkloMTVoZC9JZE5BUm03OHkvSWNvUi8KRDYrMHB3dWxTR0VQcTJIanFiM2V6T0grQUV3RWc3V2RGdk9UVzRXVTcvdC9iUXQ1enZkNjRKVktaanVEWjkrdQp6ZWFNYWtBejE1SGczR3NnQVpmci9Dd2RaMkVNK0VrYjdSWkVjNVBYa256TFdOSFRmQUZ3M0tpOXlKSCs3TmJlClYxSmxxMWtDZ1lFQWovQTROR24xdHVWMTVRdjNDN0xoSGxSbW1yNXhxRnlRVnJ3dUJ3NitQRUFUbjVQOHR5eWkKZ1BjTjJoZk5od251OUN6Zlk5YVlTWEorNVFreE9COEZlWEovWEYxUzBkazRwaGNkYnhiTmlLbnMyaXpldDloYQpDdFpiRllDUENOSE5TMlNndFZaY3ErVkhKQ1JqZ0hKUGhxeDc1aFRjMFlBQm1jV1IyRDc3V0k4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
cmd/clusterctl/examples/azure/machines_no_node.yaml.template:34:          sshPrivateKey: ${SSH_PRIVATE_KEY}
cmd/clusterctl/examples/azure/machines.yaml.template:34:          sshPrivateKey: ${SSH_PRIVATE_KEY}
cmd/clusterctl/examples/azure/machines.yaml.template:64:          sshPrivateKey: ${SSH_PRIVATE_KEY}
Binary file clusterctl matches
config/worker-machineset.yaml:39:          sshPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdUJzUjNlZnlTbmtWOUh6ZFBzWE4rY3NTcjVLS0E5S0NMeGJBYmR4dWQyU0wzakphCmVTWWdPRlRoZTI5c2FiMy8wQnBtWDJJc2NFVjlNRS91RlV1dFZsVE1obUJCenFUajNQL2RYMHF2UEp0bUovZ0cKbDBrQzBwV1dWUlNDK3BmcU01L1VBckdTTVl5V1hUSndEVXo3MTFkWTNDRWlNZkgwaVNjbmc3MXhFbWd3bkxsZQp6bnU2TURIbEdaY2ZrengzYWp2Y1JMdmFwd3hGME0rU0JEd0F0Q3lFUWJtNjIxSXVEM2dSRVVHOGp6OEdiVWFECk80eElMWncxd3E1VjVzK2pnc09iRzRUQk9BUVVHRzFkRFZnY0VjcjVhME1kcG5PaHVxM1BOcy9aU05neVFyeUsKN0hSSisrL2ozdkcyWmkxRHUxaXRSQUs4SlZuQUczakhXZ0hhT3dJREFRQUJBb0lCQVFDdDlNWDVDd1NnNGJDaApCcXAyZWFpWjhndUI0ZENPdEFWV1FRVXB5VEtIbFhXalNhaTYrQTlScXNJelE2RUllUUtSdTZBbldEZnREWHV3CmZwWFRnV0lUUktUTUEzK3FwWnE0WXZyazQwaVkxNnk2NzF3cTdrM0FkSjlMWE1vMXhmMEJNbSs4NjlQYkJaKysKQjc1Z2t2RVRFL0ZlYmVCRm1QMFo2dWtuVFlUZGdnSGNHaDFHbU1zcDlHUFcrZkJ1TmVkNGxSSkdUcU5mVWJaeApEZDFvbkJqT3Z2eDF3NDk2UHdsYTlxRkwwRlBZMkg4YjdKM1NramZmTS91RmFWbVZGbTAvQ1pWdHMvWDUzR1ZIClBId2w3ZU5lOWNIQ2VYWFFNRzk3d05LSm9wL0MyRWo3NjY4NHJSVG1QVzUxV2FWTFA2SmQ4b3k3Um00WU52dTAKd0o5bk1PaUJBb0dCQU9nd2syYTQ2ZU16OHlMV2JEdE5McnRvdjZYSEYveTI1NjBBUHQreEMvOXdyMVo3QWJSQgpBMWJkb0ZyYzJ2bDh1UnpTVW93TTc4SFNQTk5Kamg5VVVjYWhFN3pvOTRaL0RiRkFRa04rSmh6K2hWeHY2amhrClR0VXhpUVBaSDBLVFppUEpta25CZlJnUUtoWmhiN0NiL2pyZ0IrNjEzdWFkd3pGcUtZL3lEaHBSQW9HQkFNcjgKTW02TVR4dXV4aUtLTjVQYlJMbytIemVFdzNZSUlmNVIrbEluMHFhdW1KbDFTeVVmR2ZWMjdvZm93ZGlNWEtOSwpjRHE0VjhvWnhmY1l0d3U3bmgyZGxCRi9EMUtUdG5HRGd1Q3FCb1JPT0RML3hBUmp2SVdUeG42UGp3d1B3Q2lkCnl0Qko5QnpiUGtBOXl1L3N5bU1zQnBuQkUxZDJOREwvMXVXZUtEekxBb0dBZnhZdlo5Y29kV3AyMXdla0grVkUKQWVING0rVllWTU5NRlY0QUMvSGREa2lBUUFaOXpVcVVhRlJRTTh1VXMxKzM5bldNSnduaHBTWE1reDA4aEJ0agoweU5SS1dJZU1XaVRkd1FrQU1zb1UxQmdjRkwxVVQ1ZUE4VGtLTTRMbFNZV2p0b0c3LzNPMlgvbmVXNkZjcFkvClZieFB1ekdpdW5sNVlDK3FaaFpuNzdFQ2dZRUF5WlVEa0gyTzRuTURHYkloMTVoZC9JZE5BUm03OHkvSWNvUi8KRDYrMHB3dWxTR0VQcTJIanFiM2V6T0grQUV3RWc3V2RGdk9UVzRXVTcvdC9iUXQ1enZkNjRKVktaanVEWjkrdQp6ZWFNYWtBejE1SGczR3NnQVpmci9Dd2RaMkVNK0VrYjdSWkVjNVBYa256TFdOSFRmQUZ3M0tpOXlKSCs3TmJlClYxSmxxMWtDZ1lFQWovQTROR24xdHVWMTVRdjNDN0xoSGxSbW1yNXhxRnlRVnJ3dUJ3NitQRUFUbjVQOHR5eWkKZ1BjTjJoZk5od251OUN6Zlk5YVlTWEorNVFreE9COEZlWEovWEYxUzBkazRwaGNkYnhiTmlLbnMyaXpldDloYQpDdFpiRllDUENOSE5TMlNndFZaY3ErVkhKQ1JqZ0hKUGhxeDc1aFRjMFlBQm1jV1IyRDc3V0k4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
config/master-machine.yaml:28:      sshPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdUJzUjNlZnlTbmtWOUh6ZFBzWE4rY3NTcjVLS0E5S0NMeGJBYmR4dWQyU0wzakphCmVTWWdPRlRoZTI5c2FiMy8wQnBtWDJJc2NFVjlNRS91RlV1dFZsVE1obUJCenFUajNQL2RYMHF2UEp0bUovZ0cKbDBrQzBwV1dWUlNDK3BmcU01L1VBckdTTVl5V1hUSndEVXo3MTFkWTNDRWlNZkgwaVNjbmc3MXhFbWd3bkxsZQp6bnU2TURIbEdaY2ZrengzYWp2Y1JMdmFwd3hGME0rU0JEd0F0Q3lFUWJtNjIxSXVEM2dSRVVHOGp6OEdiVWFECk80eElMWncxd3E1VjVzK2pnc09iRzRUQk9BUVVHRzFkRFZnY0VjcjVhME1kcG5PaHVxM1BOcy9aU05neVFyeUsKN0hSSisrL2ozdkcyWmkxRHUxaXRSQUs4SlZuQUczakhXZ0hhT3dJREFRQUJBb0lCQVFDdDlNWDVDd1NnNGJDaApCcXAyZWFpWjhndUI0ZENPdEFWV1FRVXB5VEtIbFhXalNhaTYrQTlScXNJelE2RUllUUtSdTZBbldEZnREWHV3CmZwWFRnV0lUUktUTUEzK3FwWnE0WXZyazQwaVkxNnk2NzF3cTdrM0FkSjlMWE1vMXhmMEJNbSs4NjlQYkJaKysKQjc1Z2t2RVRFL0ZlYmVCRm1QMFo2dWtuVFlUZGdnSGNHaDFHbU1zcDlHUFcrZkJ1TmVkNGxSSkdUcU5mVWJaeApEZDFvbkJqT3Z2eDF3NDk2UHdsYTlxRkwwRlBZMkg4YjdKM1NramZmTS91RmFWbVZGbTAvQ1pWdHMvWDUzR1ZIClBId2w3ZU5lOWNIQ2VYWFFNRzk3d05LSm9wL0MyRWo3NjY4NHJSVG1QVzUxV2FWTFA2SmQ4b3k3Um00WU52dTAKd0o5bk1PaUJBb0dCQU9nd2syYTQ2ZU16OHlMV2JEdE5McnRvdjZYSEYveTI1NjBBUHQreEMvOXdyMVo3QWJSQgpBMWJkb0ZyYzJ2bDh1UnpTVW93TTc4SFNQTk5Kamg5VVVjYWhFN3pvOTRaL0RiRkFRa04rSmh6K2hWeHY2amhrClR0VXhpUVBaSDBLVFppUEpta25CZlJnUUtoWmhiN0NiL2pyZ0IrNjEzdWFkd3pGcUtZL3lEaHBSQW9HQkFNcjgKTW02TVR4dXV4aUtLTjVQYlJMbytIemVFdzNZSUlmNVIrbEluMHFhdW1KbDFTeVVmR2ZWMjdvZm93ZGlNWEtOSwpjRHE0VjhvWnhmY1l0d3U3bmgyZGxCRi9EMUtUdG5HRGd1Q3FCb1JPT0RML3hBUmp2SVdUeG42UGp3d1B3Q2lkCnl0Qko5QnpiUGtBOXl1L3N5bU1zQnBuQkUxZDJOREwvMXVXZUtEekxBb0dBZnhZdlo5Y29kV3AyMXdla0grVkUKQWVING0rVllWTU5NRlY0QUMvSGREa2lBUUFaOXpVcVVhRlJRTTh1VXMxKzM5bldNSnduaHBTWE1reDA4aEJ0agoweU5SS1dJZU1XaVRkd1FrQU1zb1UxQmdjRkwxVVQ1ZUE4VGtLTTRMbFNZV2p0b0c3LzNPMlgvbmVXNkZjcFkvClZieFB1ekdpdW5sNVlDK3FaaFpuNzdFQ2dZRUF5WlVEa0gyTzRuTURHYkloMTVoZC9JZE5BUm03OHkvSWNvUi8KRDYrMHB3dWxTR0VQcTJIanFiM2V6T0grQUV3RWc3V2RGdk9UVzRXVTcvdC9iUXQ1enZkNjRKVktaanVEWjkrdQp6ZWFNYWtBejE1SGczR3NnQVpmci9Dd2RaMkVNK0VrYjdSWkVjNVBYa256TFdOSFRmQUZ3M0tpOXlKSCs3TmJlClYxSmxxMWtDZ1lFQWovQTROR24xdHVWMTVRdjNDN0xoSGxSbW1yNXhxRnlRVnJ3dUJ3NitQRUFUbjVQOHR5eWkKZ1BjTjJoZk5od251OUN6Zlk5YVlTWEorNVFreE9COEZlWEovWEYxUzBkazRwaGNkYnhiTmlLbnMyaXpldDloYQpDdFpiRllDUENOSE5TMlNndFZaY3ErVkhKQ1JqZ0hKUGhxeDc1aFRjMFlBQm1jV1IyRDc3V0k4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go:56:	SSHPrivateKey string `json:"sshPrivateKey,omitempty"`
```

Those files too please.

**Comment by enxebre** [comment]
@ingvagabund  thanks! updated

**Pull request merged**
