### PR TITLE
OCPCLOUD-2745: Disable aso api

### PR DESCRIPTION
**Pull request by nrb**
- Remove the ASO CRDs from manifests so that we're not installing resources without a backing implementation.
- Disable the ASO controllers in CAPZ deployment

Note: Did this slightly differently than hypershift (https://github.com/openshift/hypershift/pull/5167) because I don't want to modify the upstream files we carry directly.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/approve

**Comment by shellyyang1989** [comment]
cc @sunzhaohua2 for awareness

**Comment by JoelSpeed** [comment]
Can we come up with a Kustomize patch that injects the feature gates flag as HyperShift used to rule out the env variable being ignored?

**Comment by RadekManak** [comment]
@JoelSpeed Attempting to do so in https://github.com/openshift/cluster-api-provider-azure/pull/327

**Comment by nrb** [comment]
Closed in favor of #327

**Pull request closed without merging**
