### PR TITLE
[WIP] CCO-320 followup

### PR DESCRIPTION
**Pull request by dlom**
xref: [CCO-320](https://issues.redhat.com//browse/CCO-320)

/hold

### CODE REVIEW

**Comment by newtonheath** [comment]
@dlom @JoelSpeed - where is this at?

**Comment by dlom** [comment]
@newtonheath now that the test has been added to CI, this should be simple enough to verify and close out

**Comment by newtonheath** [comment]
@JoelSpeed can you nudge this over the line - @dlom can answer any questions you may have

**Comment by JoelSpeed** [comment]
@newtonheath this is not a mergeable PR as far as I can tell. @dlom what are you trying to achieve with this?

**Comment by dlom** [comment]
Originally it was to run the azure oidc CI job on master to see if it passed, but I had to take a detour because that job didn't exist for this repo at the time. As soon as the test passes here, I'm closing this PR and the card

**Pull request closed without merging**
