### PR TITLE
[release-4.4] Bug 1810531: UPSTREAM: <carry>: openshift: Revendor MAO with timeout formatting fix

### PR DESCRIPTION
**Pull request by alexander-demichev**
Revendor MAO with timeout formatting fix in node draining log message.

### CODE REVIEW

**Comment by alexander-demichev** [comment]
@sdodson Can this PR get `cherry-pick-approved` ?

**Comment by sdodson** [comment]
@alexander-demichev Is the bug's severity set appropriately? We're having to focus on the most urgent bug fixes immediately after GA so if this is truly low it may be a while. Please make sure it's set appropriately and issue `/bugzilla refresh` Also, all the normal patch manager process applies so this wouldn't merge until the merge window opens Wed-Friday.

**Comment by alexander-demichev** [comment]
@sdodson Hi, that's not an urgent bug and I didn't know about merge window, thanks for info!

**Comment by enxebre** [comment]
cc @mfojtik

**Comment by enxebre** [comment]
@knobunc can we get this in? just a logging fix.

**Pull request merged**
