### PR TITLE
[release-4.6] Bug 1890452: Adding managed disk parameters to support DES encryption

### PR DESCRIPTION
**Pull request by kwoodson**
…rt DES encryption

This commit adds the ability to support customer supplied encryption
keys. This feature requires a disk encryption set, a key vault,
and a customer's encryption key. This feature assumes that the
disk encryption set presides in a resource group where the cloud
credentials operator has granted permissions or an additional reader
role will be required to be granted on the disk encryption
set.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/retitle [release-4.6] Bug 1890452: Adding managed disk parameters to support DES encryption

**Comment by sdodson** [comment]
(Patch Manager) This PR was reviewed for inclusion last week, however this adds feature work during the weeks immediately after release where we're focused on stability, upgrade success, and anything which blocks backports of critical customer impacting bugs. Since this doesn't meet those criteria it was not accepted last week and likely will not until we've been able to promote the 4.5 to 4.6 upgrade to the stable channel.

**Pull request merged**
