### PR TITLE
Bug 1917838: Updating Azure VMSize list from autoscaler.

### PR DESCRIPTION
**Pull request by Makdaam**
**What this PR does / why we need it**:
Updating the Azure VMSize list from the Autoscaler, there are missing VM Sizes which cause confusing Warning messages during MachineSet reconciliation.

**Special notes for your reviewer**:
Pulled a fresh list from https://github.com/openshift/kubernetes-autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go
make vet, make generate pass

**Release note**:

```release-note
Updated the list of Azure VMSizes in MachineSet actuator (July 2020).
```

### CODE REVIEW

**Comment by Makdaam** [comment]
Related BZ 
Fixed (D2as VMSize added) https://bugzilla.redhat.com/show_bug.cgi?id=1903594
Related (quickfix) https://bugzilla.redhat.com/show_bug.cgi?id=1896321

**Comment by JoelSpeed** [comment]
/approve

/retitle Bug 1917838: Updating Azure VMSize list from autoscaler.

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Pull request merged**
