### PR TITLE
Bug 1874910: Make gen fix 4.5

### PR DESCRIPTION
**Pull request by michaelgugino**
This patch set unbreaks code generation.  Using same method as master branch (currently 4.6).

Backports: https://github.com/openshift/cluster-api-provider-azure/pull/159

### CODE REVIEW

**Comment by michaelgugino** [comment]
cc @kwoodson This was more complicated than it should have been.  Go mod black magic.

**Comment by elmiko** [comment]
one of the commits has a bug in its title, s/PSTREAM/UPSTREAM/, it _may_ blow up the history script

**Pull request merged**
