### PR TITLE
Added client interfaces, carry test mocks

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
- Moving forward to unify with client tests carried from upstream. Adds necessary interfaces and automatic mock generator for adding refactored tests in the future.
- Bumps azure client lib to v. 2019-12(05)-01

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
> Had a read through, seems like sensible changes, +1 to converging with upstream
> 
> What more do you want to do?

Probably not much for this PR, only need to include mock generator to pull refactored tests with following PRs.

**Comment by alexander-demichev** [comment]
Everything else looks good, thanks a lot

**Comment by Danil-Grigorev** [comment]
/release-4.6

**Comment by Danil-Grigorev** [comment]
Tried this on azure cluster, scaled machines up and down - works for me.

**Comment by JoelSpeed** [comment]
/hold

We don't want to merge this until the master branch opens for 4.6

**Pull request closed without merging**
