### PR TITLE
OCPBUGS-2581: Fix go list for go1.18

### PR DESCRIPTION
**Pull request by lobziik**
Specify 'concrete' version of
sigs.k8s.io/cluster-api-provider-{aws|azure}
which makes go to make a correct replace in
`modules.txt` file.

### CODE REVIEW

**Comment by sdodson** [comment]
@JoelSpeed It's alarming to me that we're having to make code changes to support a build infrastructure issue related to Go 1.18 when this branch must be built with 1.15. I'm trying to get to the bottom of that with ART but is not having this merged blocking something else from shipping?

**Comment by JoelSpeed** [comment]
My understanding was that this is blocking 4.9.z nightlies from being built, which seemed pretty important to fix.

If that's not correct then I'm less rushed about merging this

**Pull request merged**
