### PR TITLE
Bug 1864352: Add leader election mechanism to release 4.5

### PR DESCRIPTION
**Pull request by elmiko**
This change brings in 3 cherry-pick commits which add leader election to this controller.

7fe5391f7092d839de96cd6de58c2f68c872c9f7
3248f7db446df02a84597a7c2302dbfa57ec72c1
201dd37fa1e3f62062b59c629e7aa1011bc85f07

### CODE REVIEW

**Comment by elmiko** [comment]
i'm putting a hold on this as i would like to make sure we include these commits when they land on the master branch, #157 
/hold

**Comment by elmiko** [comment]
removing hold as #157 has merged
/hold cancel

**Comment by elmiko** [comment]
/retitle Bug 1864352: Add leader election mechanism to release 4.5

**Comment by Danil-Grigorev** [comment]
\lgtm
\approve

**Comment by markmc** [comment]
Landed this for aws and baremetal last. Seems justified to avoid nasty failure scenario.

**Pull request merged**
