### PR TITLE
UPSTREAM: <carry>: openshift: remove kubeadm cluser configuration from clusterprovider

### PR DESCRIPTION
**Pull request by abhinavdahiya**
**What this PR does / why we need it**:

kubeadm configuration will probably wont be used for openshift and removing this import in `apis`
allows consumers in openshift to import the machine-api without importing entire kubernetes.

With this change installer can easily move off the custom fork for provider to openshift's fork example https://github.com/openshift/installer/pull/1703

### CODE REVIEW

**Comment by enxebre** [comment]
Wouldn't this be gated by `[prune] unused-packages = true` on the installer?
looking good to me @ingvagabund @awesomenix

**Comment by ingvagabund** [comment]
> Wouldn't this be gated by [prune] unused-packages = true on the installer?

It would not if you were to import azure provider spec.

/approve

leaving the lgtm flag for others.

**Comment by awesomenix** [comment]
might require a dep ensure to make sure kubeadm package is removed

**Comment by abhinavdahiya** [comment]
> might require a dep ensure to make sure kubeadm package is removed

I did run `make all` which runs dep-ensure already. there was no change for vendoring.
```
$ make all
Repository is set up correctly
bazel run //:gazelle
INFO: Invocation ID: 92e5ab90-3b53-4aa5-a371-72cf634efb11
INFO: Analysed target //:gazelle (24 packages loaded, 153 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 2.121s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: open /home/adahiya/go/src/sigs.k8s.io/cluster-api-provider-azure/vendor/k8s.io/kubernetes/BUILD.bazel: no such file or directory
Checking status of dependencies
INFO: Invocation ID: 26a9951b-e064-47d0-8262-7c63eb1955f3
INFO: Analysed target //:dep (3 packages loaded, 741 targets configured).
INFO: Found 1 target...
Target //:dep up-to-date:
  bazel-bin/dep_script
  bazel-bin/dep
INFO: Elapsed time: 1.951s, Critical Path: 0.14s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Finished verifying dependencies
GOPATH=/home/adahiya/go bazel run //:generate
INFO: Invocation ID: de4f480f-7924-42e9-a58b-1ce1e8e7cbc6
INFO: Analysed target //:generate (0 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //:generate up-to-date:
  bazel-bin/generate_script
  bazel-bin/generate
INFO: Elapsed time: 0.627s, Critical Path: 0.09s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
make dep-ensure
make[1]: Entering directory '/home/adahiya/go/src/sigs.k8s.io/cluster-api-provider-azure'
Repository is set up correctly
Checking status of dependencies
INFO: Invocation ID: a9d7488c-7dae-455e-a6ab-3336867771d4
INFO: Analysed target //:dep (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:dep up-to-date:
  bazel-bin/dep_script
  bazel-bin/dep
INFO: Elapsed time: 0.611s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Finished verifying dependencies
make[1]: Leaving directory '/home/adahiya/go/src/sigs.k8s.io/cluster-api-provider-azure'
./hack/verify_boilerplate.py
bazel test --nosandbox_debug //pkg/... //cmd/...
INFO: Invocation ID: 8896ecc1-aa4d-4a1e-9157-f420e648f95f
INFO: Build option --features has changed, discarding analysis cache.
INFO: Analysed 6 targets (448 packages loaded, 9428 targets configured).
INFO: Found 6 test targets...
INFO: Elapsed time: 1.927s, Critical Path: 0.12s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Test cases: finished with 6 passing and 0 failing out of 6 test cases

Executed 0 out of 6 tests: 6 tests pass.
INFO: Build completed successfully, 1 total action
bazel build //cmd/manager
INFO: Invocation ID: 53985f0d-5760-4e2b-a0a9-05dec1049450
INFO: Build option --features has changed, discarding analysis cache.
INFO: Analysed target //cmd/manager:manager (2 packages loaded, 9179 targets configured).
INFO: Found 1 target...
Target //cmd/manager:manager up-to-date:
  bazel-bin/cmd/manager/linux_amd64_pure_stripped/manager
INFO: Elapsed time: 1.731s, Critical Path: 0.12s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
install bazel-bin/cmd/manager/linux_amd64_*/manager /home/adahiya/go/bin/azure-manager
bazel build --workspace_status_command=./hack/print-workspace-status.sh //cmd/clusterctl
INFO: Invocation ID: 0fd9f2fd-76f2-4a84-8c48-f63f6c1410a2
INFO: Analysed target //cmd/clusterctl:clusterctl (31 packages loaded, 161 targets configured).
INFO: Found 1 target...
Target //cmd/clusterctl:clusterctl up-to-date:
  bazel-bin/cmd/clusterctl/linux_amd64_pure_stripped/clusterctl
INFO: Elapsed time: 0.879s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
install bazel-bin/cmd/clusterctl/linux_amd64_*/clusterctl /home/adahiya/go/bin/clusterctl
```

**Comment by enxebre** [comment]
not sure why doesn't let you add the label @awesomenix 
/lgtm

**Pull request merged**
