### PR TITLE
OCPBUGS-42434: Add the ability to auth via certs without storing them in etcd secret

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it:**
This is needed for ARO HCP.

Allows Service Principal with Certificate authentication to work with a path to the certificate rather than reading it from a k8s secret. This allows one to use the Secret Store CSI driver to mount a certificate from Azure Key Vault into a volume and pass that path to AzureClusterIdentity.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/approve
/lgtm

Already merged upstream so happy to have this backported

**Comment by damdo** [comment]
/hold

Let's wait for #320 to merge first

**Pull request merged**
