### PR TITLE
Update Git History check script to align with othwr repositories

### PR DESCRIPTION
**Pull request by JoelSpeed**
I've copied this updated script from the autoscaler repository. The update means that you no longer need `openshift:` in the prefix and, if you get the prefix wrong, we actually print out a message to tell you why and how to fix it.

Doing this so that the verify history script is consistent across repositories

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Comment by JoelSpeed** [comment]
I lost the executable bit when I created the commit, have pushed with the executable bit set, please LGTM again

**Pull request merged**
