### PR TITLE
Bump Azure SDK version

### PR DESCRIPTION
**Pull request by dkorzuno**
**What this PR does / why we need it**:

It bumps the azure sdk version to the latest to enable access to the most recent features.

**Special notes for your reviewer**:

This PR is a prerequisite for another PR which should allow us specify "Encryption At Host" Azure feature.

**Release note**:
NONE

### CODE REVIEW

**Comment by dkorzuno** [comment]
> Container test exited with code 1, reason Error
Last commit message didn't contain needed prefix. Offending commit message is:
Bump azure sdk version

What prefix does it expect? Is there a doc somewhere?

**Comment by elmiko** [comment]
this looks fine to me, but the commit title needs to be changed if we are carrying this as a patch on top of upstream. it should be `UPSTREAM: <carry>: openshift: Bump Azure SDK version`, unless this is a cherry-pick from upstream.

**Comment by dkorzuno** [comment]
@elmiko  we discussed that cherry-picking might be a better option here, and I was aiming to use [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/975) as the basis. However, I noticed that this repository already has `k8s/*` dependencies ahead of the upstream. Downgrading the versions probably doesn't make sense, so I ended up changing only the commit message.

**Comment by elmiko** [comment]
makes sense to me, thanks for the update @dkorzuno 
/hold cancel

**Pull request merged**
