### PR TITLE
Do not hardcode GOARCH/GOOS

### PR DESCRIPTION
**Pull request by yselkowitz**
**What this PR does / why we need it**:
This is needed for multi-arch enablement of this container image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yselkowitz** [comment]
Manifest-list images automatically pull from the native architecture, and golang automatically compiles for the native architecture.

**Comment by JoelSpeed** [comment]
So this would mean we would have to build an arm image on an arm box? Windows on a windows box etc? 
Non blocking, just for my own curiousity, but is it possible to publish all of the arch images from the same machine? Cross building? 

/lgtm

**Comment by yselkowitz** [comment]
> So this would mean we would have to build an arm image on an arm box? Windows on a windows box etc?

Yes.

> Non blocking, just for my own curiousity, but is it possible to publish all of the arch images from the same machine? Cross building?

Not feasibly.

**Comment by yselkowitz** [comment]
Obsoleted by https://github.com/openshift/cluster-api-provider-azure/commit/ab01fdecfddbefb717ef153964c8cc71c1470943

**Pull request closed without merging**
