### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api-provider-azure:release-1.7 (741a29d) into master

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
For coordination with other CAPI components:

/hold

**Review by elmiko — COMMENTED** [review]
commit history looks clean to me
/lgtm

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by elmiko — COMMENTED** [review]
/approve

**Comment by damdo** [comment]
This is a techpreview feature and it's actually not enabled on serial tests.
That's why we think we can override this job.

/override ci/prow/e2e-azure-serial

**Comment by damdo** [comment]
The main cluster-api PR merged.
/unhold

**Pull request merged**
