### PR TITLE
Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data

### PR DESCRIPTION
**Pull request by elmiko**
This PR is a copy of the autogenerated PR by the
[ocp-build-data-enforcer](https://github.com/openshift/ci-tools/tree/master/cmd/ocp-build-data-enforcer).
It updates the baseimages in the Dockerfile used for promotion in order
to ensure it matches the configuration in the [ocp-build-data
repository](https://github.com/openshift/ocp-build-data/tree/openshift-4.6-rhel-8/images)
used for producing release artifacts.

If you believe the content of this PR is incorrect, please contact the
dptp team in #forum-testplatform

### CODE REVIEW

**Comment by elmiko** [comment]
this is a reposting of #160 to correct the git commit message.

**Comment by elmiko** [comment]
/retitle Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data

**Comment by elmiko** [comment]
i updated this to add a new file after discussion with @michaelgugino and on our mailing-list.

**Comment by elmiko** [comment]
adding a reference to the dependent PR, https://github.com/openshift/ocp-build-data/pull/636

**Comment by crawford** [comment]
The e2e-azure-operator job has been failing consistently for a while, starting before this PR. Looking through individual results, I don't see a common pattern other than OpenShift on Azure generally being too slow for our CI's liking. As such, I'm going to override this test.

/override ci/prow/e2e-azure-operator

**Comment by elmiko** [comment]
thanks Alex, it looked like flakes from azure

**Pull request merged**
